# Generated by Django 3.0.7 on 2020-06-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0003_auto_20200613_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formview',
            name='ico',
            field=models.PositiveIntegerField(max_length=8),
        ),
    ]
