# Generated by Django 3.0.7 on 2020-06-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formular', '0004_auto_20200613_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formview',
            name='ico',
            field=models.CharField(max_length=8),
        ),
    ]
